In [215]:
import random
import numpy as np
import math
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.cluster import KMeans

sampling points from sphere

In [216]:
#% matplotlib inline

def sampleBallPoints(center, radius):
    
    R = radius
    
    center_x = center[0]
    center_y = center[1]
    center_z = center[2]
    
    x = []
    y = []
    z = []

    for i in range(50):

        phi = random.uniform(0,2*math.pi)
        costheta = random.uniform(-1,1)
        u = random.random()

        theta = math.acos(costheta)

        r = R*(u**(1/3))

        x.append((r * math.sin( theta) * math.cos( phi ))+center_x)
        y.append((r * math.sin( theta) * math.sin( phi ))+center_y)
        z.append((r * math.cos( theta ))+center_z)

   
    #Axes3D.scatter(x,y,z)
    return x, y, z

In [217]:
radius = 10

center1 = [0,0,0]
center2 = [0,20,0]

x1, y1, z1 = sampleBallPoints(center1,radius)
x2, y2, z2 = sampleBallPoints(center2,radius)

sphere1 = list(zip(x1, y1, z1))
sphere2 = list(zip(x2, y2, z2))

data = sphere1+sphere2

Running K Means on these two spheres

iterations to obtain centers B(c1,9) and B(c2,9)

In [218]:
from sklearn import cluster

k = 2

for i in range(1,1000,100):
    kmeans = cluster.KMeans(n_clusters=k, max_iter = i, init = 'random')
    kmeans.fit(data)

#labels = kmeans.labels_
    centroids = kmeans.cluster_centers_
    
    print("Iteration:",i)
    print(centroids)


Iteration: 1
[[ -0.30949961  20.83627548  -0.23400951]
 [  0.86045873   1.86827897  -0.53373614]]
Iteration: 101
[[ -0.07016874  20.0358504   -0.27526018]
 [  0.73812369   0.77190441  -0.52245813]]
Iteration: 201
[[  0.73812369   0.77190441  -0.52245813]
 [ -0.07016874  20.0358504   -0.27526018]]
Iteration: 301
[[  0.73812369   0.77190441  -0.52245813]
 [ -0.07016874  20.0358504   -0.27526018]]
Iteration: 401
[[  0.73812369   0.77190441  -0.52245813]
 [ -0.07016874  20.0358504   -0.27526018]]
Iteration: 501
[[ -0.07016874  20.0358504   -0.27526018]
 [  0.73812369   0.77190441  -0.52245813]]
Iteration: 601
[[  0.73812369   0.77190441  -0.52245813]
 [ -0.07016874  20.0358504   -0.27526018]]
Iteration: 701
[[ -0.07016874  20.0358504   -0.27526018]
 [  0.73812369   0.77190441  -0.52245813]]
Iteration: 801
[[ -0.07016874  20.0358504   -0.27526018]
 [  0.73812369   0.77190441  -0.52245813]]
Iteration: 901
[[ -0.07016874  20.0358504   -0.27526018]
 [  0.73812369   0.77190441  -0.52245813]]


Cost function as function of iterations

In [219]:
for i in range(1,100):
    kmeans = cluster.KMeans(n_clusters=k, max_iter = i, init = 'random')
    kmeans.fit(data)

#labels = kmeans.labels_
    costFunction = kmeans.inertia_
    
    print("Iteration:",i)
    print(costFunction)


Iteration: 1
5816.50930565
Iteration: 2
5816.50930565
Iteration: 3
5816.50930565
Iteration: 4
5816.50930565
Iteration: 5
5816.50930565
Iteration: 6
5816.50930565
Iteration: 7
5816.50930565
Iteration: 8
5816.50930565
Iteration: 9
5816.50930565
Iteration: 10
5816.50930565
Iteration: 11
5816.50930565
Iteration: 12
5816.50930565
Iteration: 13
5816.50930565
Iteration: 14
5816.50930565
Iteration: 15
5816.50930565
Iteration: 16
5816.50930565
Iteration: 17
5816.50930565
Iteration: 18
5816.50930565
Iteration: 19
5816.50930565
Iteration: 20
5816.50930565
Iteration: 21
5816.50930565
Iteration: 22
5816.50930565
Iteration: 23
5816.50930565
Iteration: 24
5816.50930565
Iteration: 25
5816.50930565
Iteration: 26
5816.50930565
Iteration: 27
5816.50930565
Iteration: 28
5816.50930565
Iteration: 29
5816.50930565
Iteration: 30
5816.50930565
Iteration: 31
5816.50930565
Iteration: 32
5816.50930565
Iteration: 33
5816.50930565
Iteration: 34
5816.50930565
Iteration: 35
5816.50930565
Iteration: 36
5816.50930565
I

sensitivity to initial choice of centers

In [220]:
initCenters1 = np.array([[10,0,0],[0,20,0]],np.float64)
initCenters2 = np.array([[0,15,0],[-10,20,0]],np.float64)
initCenters3 = np.array([[3,5,1],[0,20,-1]],np.float64)
initCenters4 = np.array([[20,4,0],[0,2,0]],np.float64)
initCenters5 = np.array([[0,0,0],[3,-2,10]],np.float64)

kmeans1 = cluster.KMeans(n_clusters=k, max_iter = 10, init = initCenters1)
kmeans1.fit(data)
costFunction1 = kmeans.inertia_
print(initCenters1,costFunction1)

kmeans2 = cluster.KMeans(n_clusters=k, max_iter = 10, init = initCenters2)
kmeans2.fit(data)
costFunction2 = kmeans.inertia_
print(initCenters2,costFunction2)

kmeans3 = cluster.KMeans(n_clusters=k, max_iter = 10, init = initCenters3)
kmeans3.fit(data)
costFunction3 = kmeans.inertia_
print(initCenters3,costFunction3)

kmeans4 = cluster.KMeans(n_clusters=k, max_iter = 10, init = initCenters4)
kmeans4.fit(data)
costFunction4 = kmeans.inertia_
print(initCenters4,costFunction4)

kmeans5 = cluster.KMeans(n_clusters=k, max_iter = 10, init = initCenters5)
kmeans5.fit(data)
costFunction5 = kmeans.inertia_
print(initCenters5,costFunction5)

[[ 10.   0.   0.]
 [  0.  20.   0.]] 5816.50930565
[[  0.  15.   0.]
 [-10.  20.   0.]] 5816.50930565
[[  3.   5.   1.]
 [  0.  20.  -1.]] 5816.50930565
[[ 20.   4.   0.]
 [  0.   2.   0.]] 5816.50930565
[[  0.   0.   0.]
 [  3.  -2.  10.]] 5816.50930565


/Users/tarunruchandani/anaconda/lib/python3.5/site-packages/sklearn/cluster/k_means_.py:821: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  n_jobs=self.n_jobs)
